import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";

export const metadata: Metadata = { title: "Sobre Luis Hernandez y Lumina Summit Growth", description: "Conoce al fundador de Lumina Summit Growth y los principios que guían esta práctica de crecimiento.", alternates: { canonical: "/es/about", languages: { "en-US": "/about", "es-US": "/es/about" } } };

export default function SpanishAboutPage() {
  return <main id="main-content" lang="es"><section className="relative overflow-hidden bg-charcoal px-6 pb-24 pt-40 text-cream lg:px-8 lg:pb-32"><SiteHeader locale="es"/><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-gold">Sobre Lumina Summit Growth</p><h1 className="mt-6 max-w-5xl font-display text-6xl leading-[.82] sm:text-8xl">Un socio de crecimiento<br /><em className="font-normal text-gold">construido para el trabajo.</em></h1><p className="mt-9 max-w-2xl text-lg leading-8 text-cream/70">Estrategia e implementación lideradas por el fundador para negocios locales de servicios que necesitan que su visibilidad, sitio web, seguimiento y medición funcionen como un solo sistema.</p></div></section><section className="px-6 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Luis Hernandez / Fundador</p><h2 className="mt-5 font-display text-6xl leading-[.88]">Curiosidad entre disciplinas.<br />Responsabilidad en un solo lugar.</h2></div><div className="space-y-6 text-base leading-8 text-charcoal/70"><p>Luis está construyendo Lumina Summit Growth sobre una convicción sencilla: la experiencia debe ayudar a los dueños de negocios a ver el camino con claridad, no hacerlos depender de más ruido.</p><p>La práctica reúne posicionamiento, diseño de experiencia, generación de demanda, automatización y medición en un sistema operativo deliberado. El objetivo no es vender cada táctica, sino identificar la limitación que importa, construir lo que la resuelve y hacer visible el resultado.</p><p>Como fundador hispano, Luis está formando una compañía ambiciosa sin perder calidez. Lumina es honesta sobre su etapa inicial y hará crecer su portafolio mediante trabajo documentado y prueba ganada con el tiempo, no afirmaciones prestadas.</p></div></div></section><section className="bg-[#eee7d9] px-6 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div className="relative min-h-[30rem]"><Image src="/images/brand/summit-path.png" alt="Un sendero de montaña que representa progreso deliberado y medible" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div><div className="lg:pl-10"><p className="eyebrow">Principios de trabajo</p><div className="mt-8 divide-y divide-charcoal/15">{[["01","Claridad antes que tácticas"],["02","Sistemas sobre silos"],["03","Evidencia sobre espectáculo"],["04","Tecnología al servicio de las personas"]].map(([number,value])=><p key={number} className="flex gap-6 py-5"><span className="font-display text-2xl text-terracotta">{number}</span><span className="font-display text-3xl">{value}</span></p>)}</div><Link href="/es/contact" className="mt-8 inline-flex bg-charcoal px-6 py-4 text-xs font-bold uppercase tracking-[.14em] text-cream">Inicia una conversación →</Link></div></div></section><SiteFooter locale="es"/></main>;
}
