import type { Metadata } from "next";
import { ArrowRight } from "lucide-react";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { LinkButton } from "@/components/ui/link-button";
import { services } from "@/lib/constants";

export const metadata: Metadata = { title: "Servicios de Crecimiento para Negocios Locales", description: "Búsqueda local, sitios web, automatización, demanda pagada, CRM y estrategia de crecimiento para negocios de servicios.", alternates: { canonical: "/es/services", languages: { "en-US": "/services", "es-US": "/es/services" } } };

const cards = [
  ["Presencia en Búsqueda Local", "Aparece en los momentos en que tu mercado busca, desde mapas hasta resultados orgánicos."], ["Sitios Web de Conversión", "Experiencias digitales de alta confianza diseñadas para generar acción."],
  ["Demanda Pagada", "Campañas disciplinadas que convierten atención en conversaciones calificadas."], ["Automatización con IA", "Sistemas inteligentes que reducen el tiempo de respuesta y protegen cada oportunidad."],
  ["Sistemas de Ingresos", "CRM e infraestructura de seguimiento que hacen el crecimiento medible y repetible."], ["Estrategia de Crecimiento", "Prioridades claras, mejores decisiones y un plan operativo real para escalar."],
] as const;
const details = [
  ["Optimización del Perfil de Empresa de Google", "Conviértete en la opción local evidente en Maps y en los momentos en que el comprador está listo para actuar."], ["SEO Local", "Construye autoridad local, relevancia de categoría y visibilidad que se fortalece con el tiempo."],
  ["Diseño de Sitios Web", "Una presencia digital de alta confianza diseñada alrededor de cómo deciden tus compradores."], ["Páginas de Destino", "Destinos enfocados que convierten la atención pagada en conversaciones calificadas."],
  ["Meta Ads", "Creatividad, segmentación y medición disciplinadas para generar demanda."], ["Automatización con IA", "Atención receptiva de oportunidades e inteligencia operativa que mantienen el avance."],
  ["Sistemas CRM", "Un registro claro para oportunidades, seguimiento, visibilidad del embudo y responsabilidad del equipo."], ["Estrategia de Crecimiento", "Decisiones prácticas, prioridades y ritmo operativo necesarios para escalar de forma rentable."],
];

export default function SpanishServicesPage() { return <main id="main-content" lang="es"><section className="relative overflow-hidden bg-charcoal px-6 pb-24 pt-40 text-cream lg:px-8 lg:pb-32"><div className="grain absolute inset-0 opacity-20" /><SiteHeader locale="es"/><div className="relative mx-auto max-w-7xl"><p className="eyebrow text-gold">El sistema de crecimiento Lumina</p><h1 className="mt-6 max-w-5xl font-display text-6xl leading-[.8] tracking-[-.04em] sm:text-8xl">Cada palanca.<br /><em className="font-normal text-gold">Una dirección.</em></h1><p className="mt-9 max-w-xl text-base leading-7 text-cream/70">Reunimos las partes fragmentadas del crecimiento local en un sistema deliberado y conectado alrededor de tus objetivos de ingresos.</p></div></section><section className="px-6 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid border-l border-t border-charcoal/15 md:grid-cols-2 lg:grid-cols-3">{services.map(({ number, icon: Icon }, index) => <article key={number} className="min-h-60 border-b border-r border-charcoal/15 p-7"><div className="flex items-start justify-between"><span className="font-display text-2xl text-terracotta">{number}</span><Icon size={21} className="text-agave" strokeWidth={1.4} /></div><h2 className="mt-12 font-display text-3xl leading-none">{cards[index][0]}</h2><p className="mt-4 text-sm leading-6 text-charcoal/65">{cards[index][1]}</p></article>)}</div></div></section><section className="bg-[#eee7d9] px-6 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="eyebrow">Cómo ayudamos</p><div className="mt-10 divide-y divide-charcoal/15">{details.map(([title, description], index) => <article key={title} className="grid gap-5 py-7 md:grid-cols-[.12fr_.88fr] lg:grid-cols-[.1fr_.45fr_.45fr]"><span className="font-display text-2xl text-terracotta">0{index + 1}</span><h2 className="font-display text-3xl leading-none">{title}</h2><p className="max-w-md text-sm leading-6 text-charcoal/65">{description}</p></article>)}</div></div></section><section className="px-6 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 bg-agave p-8 text-cream sm:p-12 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><p className="eyebrow text-gold">Comienza con claridad</p><h2 className="mt-5 font-display text-5xl leading-[.85] sm:text-6xl">¿No sabes por dónde empezar?</h2><p className="mt-6 max-w-lg text-sm leading-6 text-cream/70">Identificaremos primero las limitaciones que vale la pena resolver, antes de recomendar tácticas.</p></div><div className="lg:justify-self-end"><LinkButton href="/es/free-audit" variant="light">Solicita una auditoría <ArrowRight size={15} /></LinkButton></div></div></section><SiteFooter locale="es"/></main>; }
