import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";

export const metadata: Metadata = { title: "About Luis Hernandez and Lumina Summit Growth", description: "Meet the founder behind Lumina Summit Growth and the principles guiding this founder-led growth practice.", alternates: { canonical: "/about", languages: { "en-US": "/about", "es-US": "/es/about", "x-default": "/about" } } };

export default function AboutPage() {
  return <main id="main-content"><section className="relative overflow-hidden bg-charcoal px-6 pb-24 pt-40 text-cream lg:px-8 lg:pb-32"><SiteHeader /><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-gold">About Lumina Summit Growth</p><h1 className="mt-6 max-w-5xl font-display text-6xl leading-[.82] sm:text-8xl">A growth partner<br /><em className="font-normal text-gold">built for the work.</em></h1><p className="mt-9 max-w-2xl text-lg leading-8 text-cream/70">Founder-led strategy and implementation for local service businesses that need their visibility, website, follow-up, and measurement to work as one system.</p></div></section><section className="px-6 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Luis Hernandez / Founder</p><h2 className="mt-5 font-display text-6xl leading-[.88]">Curiosity across disciplines.<br />Accountability in one place.</h2></div><div className="space-y-6 text-base leading-8 text-charcoal/70"><p>Luis created Lumina Summit Growth around a simple belief: local businesses should not need to coordinate a collection of disconnected specialists to understand what is driving growth.</p><p>The practice brings positioning, experience design, demand generation, automation, and measurement into one deliberate operating system. The goal is not to sell every tactic. It is to identify the constraint that matters, build what solves it, and make the result easier to see.</p><p>Lumina is early by design and honest about that stage. Its portfolio will grow through documented work, thoughtful partnerships, and proof earned over time—not borrowed claims.</p></div></div></section><section className="bg-[#eee7d9] px-6 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div className="relative min-h-[30rem]"><Image src="/images/brand/summit-path.png" alt="A mountain path representing deliberate, measurable progress" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div><div className="lg:pl-10"><p className="eyebrow">Working principles</p><div className="mt-8 divide-y divide-charcoal/15">{[["01","Clarity before tactics"],["02","Systems over silos"],["03","Evidence over theater"],["04","Technology in service of people"]].map(([number,value])=><p key={number} className="flex gap-6 py-5"><span className="font-display text-2xl text-terracotta">{number}</span><span className="font-display text-3xl">{value}</span></p>)}</div><Link href="/contact" className="mt-8 inline-flex bg-charcoal px-6 py-4 text-xs font-bold uppercase tracking-[.14em] text-cream">Start a conversation →</Link></div></div></section><SiteFooter /></main>;
}
