"use client";

import { FormEvent, useState } from "react";
import { track } from "@/lib/analytics";
import type { Locale } from "@/lib/i18n";

export function ContactForm({ locale = "en" }: { locale?: Locale }) {
  const spanish = locale === "es";
  const [status,setStatus]=useState<"idle"|"sending"|"sent"|"error">("idle");
  const [message,setMessage]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus("sending");setMessage("");const formData=new FormData(event.currentTarget);const payload={...Object.fromEntries(formData.entries()),consent:formData.get("consent")==="on",locale};try{const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json() as {message?:string};if(!response.ok)throw new Error(data.message);track("contact_form_submitted");setStatus("sent");}catch(error){track("contact_form_error");setStatus("error");setMessage(error instanceof Error?error.message:(spanish?"No pudimos enviar tu mensaje.":"We could not send your message."));}}
  if(status==="sent")return <div role="status" className="border border-charcoal/15 bg-cream p-10"><p className="eyebrow">{spanish?"Mensaje recibido":"Message received"}</p><h2 className="mt-4 font-display text-5xl">{spanish?"Gracias por comunicarte.":"Thank you for reaching out."}</h2><p className="mt-5 text-sm leading-6 text-charcoal/65">{spanish?"Tu mensaje ha sido entregado. Lumina Summit Growth responderá usando el correo electrónico que proporcionaste.":"Your note has been delivered. Lumina Summit Growth will follow up using the email you provided."}</p></div>;
  const inputClass="mt-2 min-h-12 w-full border border-charcoal/20 bg-white/55 px-4 py-3 text-base font-normal normal-case tracking-normal outline-none transition placeholder:text-charcoal/35 hover:border-charcoal/35 focus:border-terracotta focus:ring-2 focus:ring-terracotta/15";
  const optional=<span className="ml-1 font-normal normal-case tracking-normal text-charcoal/40">({spanish?"opcional":"optional"})</span>;
  return <form onSubmit={submit} className="border border-charcoal/15 bg-cream p-6 shadow-[10px_10px_0_#C89B3C] sm:p-10"><div aria-hidden="true" className="absolute -left-[10000px]"><input name="companyWebsite" tabIndex={-1} autoComplete="off" /></div><div className="grid gap-7 sm:grid-cols-2"><label className="text-xs font-semibold uppercase tracking-[.13em]">{spanish?"Nombre":"Name"} *<input name="name" required minLength={2} autoComplete="name" className={inputClass}/></label><label className="text-xs font-semibold uppercase tracking-[.13em]">{spanish?"Correo electrónico":"Email"} *<input name="email" type="email" required autoComplete="email" className={inputClass}/></label><label className="text-xs font-semibold uppercase tracking-[.13em]">{spanish?"Empresa":"Company"}{optional}<input name="company" autoComplete="organization" className={inputClass}/></label><label className="text-xs font-semibold uppercase tracking-[.13em]">{spanish?"Sitio web":"Website"}{optional}<input name="website" type="url" placeholder="https://" className={inputClass}/></label></div><label className="mt-8 block text-xs font-semibold uppercase tracking-[.13em]">{spanish?"¿Qué te gustaría construir o mejorar?":"What would you like to build or improve?"} *<textarea name="message" required minLength={20} rows={6} className={inputClass}/></label><label className="mt-6 flex cursor-pointer items-start gap-3 text-xs leading-5 text-charcoal/65"><input name="consent" type="checkbox" required className="mt-0.5 h-4 w-4 shrink-0 accent-terracotta"/><span>{spanish?"Acepto que Lumina Summit Growth me contacte sobre esta consulta. *":"I agree that Lumina Summit Growth may contact me about this inquiry. *"}</span></label>{status==="error"&&<p role="alert" className="mt-5 border-l-2 border-terracotta pl-4 text-sm text-terracotta">{message}</p>}<button disabled={status==="sending"} className="mt-7 min-h-12 w-full bg-charcoal px-6 py-4 text-xs font-bold uppercase tracking-[.14em] text-cream transition hover:bg-terracotta disabled:opacity-60">{status==="sending"?(spanish?"Enviando…":"Sending…"):(spanish?"Enviar tu consulta →":"Send your inquiry →")}</button></form>;
}
