import Link from "next/link";
import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import type { IndustryPageConfig } from "@/types/industry";
import { LandingPageTracker } from "@/components/landing-page-tracker";

export function IndustryPage({ industry }: { industry: IndustryPageConfig }) {
  return <main id="main-content">
    <LandingPageTracker pageType="industry" industry={industry.slug} />
    <section className="relative overflow-hidden bg-charcoal px-6 pb-24 pt-40 text-cream lg:px-8 lg:pb-32"><div className="grain absolute inset-0 opacity-20"/><SiteHeader/><div className="relative mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-gold">{industry.eyebrow}</p><h1 className="mt-6 max-w-5xl font-display text-6xl leading-[.82] sm:text-8xl">{industry.headline}<br/><em className="font-normal text-gold">{industry.headlineEmphasis}</em></h1><p className="mt-9 max-w-2xl text-lg leading-8 text-cream/70">{industry.introduction}</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/free-audit" className="bg-gold px-6 py-4 text-xs font-bold uppercase tracking-[.14em] text-charcoal hover:bg-cream">Apply for a growth audit →</Link><Link href="/start-here" className="border border-cream/25 px-6 py-4 text-xs font-bold uppercase tracking-[.14em] hover:border-gold">Review the Foundation Sprint</Link></div></div></section>

    <section className="px-6 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><p className="eyebrow">How demand appears</p><div className="mt-8 grid gap-px bg-charcoal/15 md:grid-cols-3">{industry.demandContexts.map((context,index)=><article key={context.title} className="min-h-64 bg-cream p-7"><span className="font-display text-2xl text-terracotta">0{index+1}</span><h2 className="mt-14 font-display text-4xl">{context.title}</h2><p className="mt-4 text-sm leading-6 text-charcoal/65">{context.description}</p></article>)}</div></div></section>

    <section className="bg-[#eee7d9] px-6 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">Where growth can be lost</p><h2 className="mt-5 font-display text-6xl leading-[.88]">The leak is rarely one tactic.</h2></div><div className="grid gap-px bg-charcoal/15 sm:grid-cols-2">{industry.constraints.map((constraint)=><article key={constraint.title} className="bg-[#eee7d9] p-6"><h3 className="font-display text-3xl">{constraint.title}</h3><p className="mt-4 text-sm leading-6 text-charcoal/65">{constraint.description}</p></article>)}</div></div></div></section>

    <section className="bg-agave px-6 py-24 text-cream lg:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-gold">What the Sprint examines</p><h2 className="mt-5 font-display text-6xl leading-[.88]">From discovery to won work.</h2><p className="mt-7 max-w-lg text-base leading-7 text-cream/70">The audit follows the customer journey and operating system. It does not assume the answer is a new website, more advertising, or more automation.</p></div><ul className="divide-y divide-cream/15 border-t border-cream/15">{industry.evaluationFocus.map((item,index)=><li key={item} className="flex gap-5 py-5 text-sm leading-6 text-cream/75"><span className="font-display text-2xl text-gold">0{index+1}</span>{item}</li>)}</ul></div></section>

    <section className="px-6 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-2"><div><p className="eyebrow">Trust before the estimate</p><h2 className="mt-5 font-display text-6xl leading-[.88]">Make confidence easier to earn.</h2><ul className="mt-8 space-y-4">{industry.trustQuestions.map((question)=><li key={question} className="border-l-2 border-terracotta pl-5 text-sm leading-6 text-charcoal/70">{question}</li>)}</ul></div><div><p className="eyebrow">Measurement after the click</p><h2 className="mt-5 font-display text-6xl leading-[.88]">Define what progress means.</h2><ul className="mt-8 grid gap-px bg-charcoal/15 sm:grid-cols-2">{industry.measurementQuestions.map((question)=><li key={question} className="bg-cream p-5 text-sm leading-6 text-charcoal/70">{question}</li>)}</ul></div></div></section>

    <section className="bg-terracotta px-6 py-20 text-cream lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-gold">{industry.audience}</p><h2 className="mt-4 font-display text-6xl leading-[.88]">Start with the constraint you can see.</h2></div><div><p className="text-sm leading-6 text-cream/75">Share your market, current lead sources, and where the customer journey feels inconsistent. We’ll review whether a Foundation Sprint is a useful next step.</p><Link href="/free-audit" className="mt-7 inline-flex bg-cream px-6 py-4 text-xs font-bold uppercase tracking-[.14em] text-charcoal hover:bg-gold">Apply for a growth audit →</Link></div></div></section>
    <SiteFooter/>
  </main>;
}
